#!/bin/bash

mv temp_1_chem_hyd_out_results.tsv test_1_chem_hyd_out_results.tsv 
mv temp_1_chem_dnazyme_out_results.tsv test_1_chem_dnazyme_out_results.tsv 
mv temp_2_chem_labRP_out_results.tsv test_2_chem_labRP_out_results.tsv 
mv temp_2_chem_dnazyme_out_results.tsv test_2_chem_dnazyme_out_results.tsv
mv temp_2_chem_dnazymeDS_out_results.tsv test_2_chem_dnazymeDS_out_results.tsv
mv temp_3_chem_hyd_out_results.tsv test_3_chem_hyd_out_results.tsv
mv temp_3_chem_labRP_out_results.tsv test_3_chem_labRP_out_results.tsv
mv temp_3_chem_dnazyme_out_results.tsv test_3_chem_dnazyme_out_results.tsv
mv temp_3_chem_dnazymeDS_out_results.tsv test_3_chem_dnazymeDS_out_results.tsv
mv temp_4_chem_labRP_out_results.tsv test_4_chem_labRP_out_results.tsv
mv temp_4_chem_dnazyme_out_results.tsv test_4_chem_dnazyme_out_results.tsv

echo "Updated all chemistry tests to temp version"
